version: "3"

networks:
  traefik-public:
    external: true

services:
  traefik:
    image: traefik:v2.5
    command: --configFile=/etc/traefik/traefik.yml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
    networks:
      - traefik-public
