version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.3
    command:
      - --api.insecure=false
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
    networks:
      - web
