version: "3"

networks:
  traefik-public:
    external: true

services:
  traefik:
    image: traefik:v2.5

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
    networks:
      - traefik-public
