version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
