version: "3"

networks:
  traefik-public:
    external: true

services:
  traefik:
    image: traefik:v2.5

    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ewfewefwe@dslkdlk.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`appleglobalprices.com`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$2y$$05$$6m8MvyzgJ4Kl7/3rL4X6VurX1huMas8a7oPB3x"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
    networks:
      - traefik-public
