api:
  dashboard: true
  insecure: false

log:
  level: DEBUG

entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "your-email@example.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: websecure

http:
  routers:
    dashboard:
      rule: "PathPrefix(`/dashboard`)"
      entrypoints:
        - "websecure"
      service: "api@internal"
      tls:
        certResolver: "myresolver"
