api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: true
      email: ewfewefwe@dslkdlk.com
      storage: /etc/traefik/acme/acme.json

http:
  routers:
    traefik:
      rule: Host(`appleglobalprices.com`) && PathPrefix(`/traefik`)
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: myresolver
      middlewares:
        - traefik-auth
  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - user:$$2y$$05$$6m8MvyzgJ4Kl7/3rL4X6VurX1huMas8a7oPB3x
