api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    basic-auth:
      basicAuth:
        users:
          - "master:$2y$05$ch15izrKErZJ3iwEPcVKOOR7kshqV5hjZdc0gjH6qQfJwiXULTJTy"

  routers:
    traefik:
      rule: "PathPrefix(`/traefik`)"
      service: "api@internal"
      middlewares:
        - "basic-auth"
      entrypoints:
        - "websecure"

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entrypoints:
        - "web"
      middlewares:
        - "redirect-to-https"
      service: "noop@internal"
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: "jlkh8i7zihzfjj8@yahoo.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web
