api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "jlkh8i7zihzfjj8@yahoo.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

http:
  routers:
    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entrypoints:
        - "web"
      middlewares:
        - "redirect-to-https"
      service: "noop@internal"

middlewares:
  redirect-to-https:
    redirectScheme:
      scheme: "https"
